version: '3.7'

services:
  sonet_back:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
  sonet-db:
    image: postgres:14.6-alpine
    volumes:
      - sonet_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  cache:
    image: redis:6.2-alpine
    restart: always 
    ports: 
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local
  sonet_postgres_data: